# -*- coding: utf-8 -*-
"""Generated derived interior layouts for #1513 vehicles with none authored.

Do not edit by hand.  Run
``tools/bake_internal_layout_derived_0922.py "$WOT_0922_CLIENT"`` to
regenerate it against the pinned client.

These layouts are DERIVED, not extracted.  No World of Tanks PC client ships
interior module geometry -- it lives in the ``collision/`` server models,
which no package contains -- so each entry carries the archetype of the #1513
vehicle this one most resembles, chosen by discriminators read from the exact
client: crew roster, fighting-compartment architecture, class, tier,
open-topped turret, turret count and where the turret ring sits along the
hull.  The donor's normalized zones are re-anchored and clipped inside this
vehicle's own collision volume at runtime, so the container is exact and only
the placement within it is archetypal.  Every record reports
``confidence = 'derived-low'``.

Each value is ``(donor profile key, vehicle class, tier, crew roster, crew
slot sources)``.  A crew slot source is ``(donor crew zone index, reuse
ordinal)``; ordinal 0 takes the donor zone as authored, and a higher ordinal
means an earlier slot already claimed it so the runtime offsets this crewman
laterally from the hull centreline instead.
"""

CLIENT_VERSION = '0.9.22.0.1'
CLIENT_BUILD = '1513'
CATALOGUE_SIZE = 680
RESOLVED_BEFORE_DERIVATION = 318
DERIVED_COUNT = 359
DERIVED_CONFIDENCE = 'derived-low'

DERIVED_LAYOUTS_0922 = {
    ('china', 'ch01type59gold'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch03wz111a'): (
        ('usa', 't5758'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch04t341'): (
        ('uk', 'gb24centurionmk3'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch04t341training'): (
        ('uk', 'gb24centurionmk3'),
        'mediumTank',
        1,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch05t342'): (
        ('ussr', 't44'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch06renaultnc31'): (
        ('ussr', 'valentinell'),
        'lightTank',
        1,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('china', 'ch06renaultnc31bot'): (
        ('ussr', 'valentinell'),
        'lightTank',
        1,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('china', 'ch07vickersmketypebt26'): (
        ('germany', 'vk2801'),
        'lightTank',
        2,
        (('commander', 'radioman'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('china', 'ch08type97chiha'): (
        ('germany', 'pz35t'),
        'lightTank',
        3,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('china', 'ch08type97chihabootcamp'): (
        ('germany', 'pz35t'),
        'lightTank',
        2,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('china', 'ch09m5'): (
        ('ussr', 't46'),
        'lightTank',
        4,
        (('commander', 'loader'), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('china', 'ch10is2'): (
        ('ussr', 'is3'),
        'heavyTank',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch11110'): (
        ('ussr', 'is'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch11110igr'): (
        ('ussr', 'is'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch12111123'): (
        ('ussr', 'is'),
        'heavyTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch14t343'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch155916'): (
        ('ussr', 't46'),
        'lightTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('china', 'ch16wz131'): (
        ('ussr', 't46'),
        'lightTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('china', 'ch17wz1311wz132'): (
        ('germany', 'vk2801'),
        'lightTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('china', 'ch17wz1311wz132igr'): (
        ('germany', 'vk2801'),
        'lightTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('china', 'ch18wz120'): (
        ('ussr', 't44'),
        'mediumTank',
        9,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch19121'): (
        ('china', 'ch01type59'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch19121igr'): (
        ('china', 'ch01type59'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch20type58'): (
        ('uk', 'gb22comet'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('china', 'ch21t34'): (
        ('ussr', 't34'),
        'mediumTank',
        5,
        (('commander', 'gunner'), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch22113'): (
        ('usa', 't14'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('china', 'ch22113p'): (
        ('usa', 't14'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('china', 'ch22113beijingopera'): (
        ('usa', 't14'),
        'heavyTank',
        10,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('china', 'ch23112'): (
        ('china', 'ch03wz111'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch24type64'): (
        ('usa', 't21'),
        'lightTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('china', 'ch25121mod1971b'): (
        ('ussr', 't44'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch2659patton'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch28wz132a'): (
        ('usa', 'm7med'),
        'lightTank',
        9,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('china', 'ch29type62cprot'): (
        ('china', 'ch02type62'),
        'lightTank',
        10,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('china', 'ch30t26gft'): (
        ('ussr', 'at1'),
        'AT-SPG',
        2,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (2, 1)),
    ),
    ('china', 'ch31m3gft'): (
        ('france', 'fcm36pak40'),
        'AT-SPG',
        3,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('china', 'ch32su76gft'): (
        ('ussr', 'su101'),
        'AT-SPG',
        4,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('china', 'ch3360gft'): (
        ('germany', 'jagdpantherii'),
        'AT-SPG',
        5,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('china', 'ch34wz131gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        6,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch35t342gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch36wz1111gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch37wz111gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        9,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch38wz113gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        10,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch39wz1201gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch40wz120gft'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        9,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('china', 'ch41wz1115a'): (
        ('usa', 't5758'),
        'heavyTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('czech', 'cz01skodat40'): (
        ('germany', 't25'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('czech', 'cz02tvpt50'): (
        ('uk', 'gb07matilda'),
        'mediumTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('czech', 'cz03ltvz35'): (
        ('germany', 'pz35t'),
        'lightTank',
        2,
        (('commander', 'gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('czech', 'cz04t5051'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('czech', 'cz05t34100'): (
        ('ussr', 't3485'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('czech', 'cz06kolohousenka'): (
        ('france', 'renaultft'),
        'lightTank',
        1,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('czech', 'cz07tvp46'): (
        ('ussr', 't3485'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('czech', 'cz08t25'): (
        ('ussr', 't3485'),
        'mediumTank',
        6,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (3, 0), (2, 0)),
    ),
    ('czech', 'cz09t24'): (
        ('ussr', 't3485'),
        'mediumTank',
        5,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (3, 0), (2, 0)),
    ),
    ('czech', 'cz10ltvz38'): (
        ('germany', 'pz38t'),
        'lightTank',
        3,
        (('commander', 'gunner'), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('czech', 'cz11v8h'): (
        ('ussr', 't28'),
        'mediumTank',
        4,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (3, 0), (2, 0)),
    ),
    ('france', 'f11renaultg1r'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        5,
        (('commander', 'gunner'), ('loader',), ('driver',), ('radioman',)),
        ((0, 0), (4, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f44somuas35'): (
        ('ussr', 't3485'),
        'mediumTank',
        3,
        (('commander', 'gunner', 'loader'), ('driver',), ('radioman', 'loader')),
        ((0, 0), (3, 0), (2, 0)),
    ),
    ('france', 'f49renaultr35'): (
        ('usa', 'm2lt'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('france', 'f50fcm3620t'): (
        ('ussr', 'valentinell'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('france', 'f66amxobam105'): (
        ('germany', 'hummel'),
        'SPG',
        4,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (4, 0), (5, 0)),
    ),
    ('france', 'f67batchatillon15555'): (
        ('france', 'batchatillon155'),
        'SPG',
        9,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (3, 1)),
    ),
    ('france', 'f68amxchasseurdechar46'): (
        ('uk', 'gb68matildablackprince'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f69amx1357100'): (
        ('france', 'amx1375'),
        'lightTank',
        7,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('france', 'f69amx1357100grandfinal'): (
        ('france', 'amx1375'),
        'lightTank',
        7,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('france', 'f70sarl42'): (
        ('uk', 'gb24centurionmk3'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f71amx30prototype'): (
        ('ussr', 't44'),
        'mediumTank',
        9,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f72amx30'): (
        ('uk', 'gb23centurion'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f73m4a1revalorise'): (
        ('usa', 'm4a3e8sherman'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('france', 'f74amxm41949'): (
        ('germany', 'lowe'),
        'heavyTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('france', 'f74amxm41949liberte'): (
        ('germany', 'lowe'),
        'heavyTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('france', 'f75charde25t'): (
        ('usa', 't2med'),
        'mediumTank',
        9,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('france', 'f81charde65t'): (
        ('ussr', 'kv4'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('loader',), ('radioman',)),
        ((0, 0), (2, 0), (1, 0), (4, 0), (3, 0)),
    ),
    ('france', 'f82amxm4mle1949ter'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        10,
        (('commander',), ('driver',), ('gunner',), ('loader',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('france', 'f83amxm4mle1949bis'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        9,
        (('commander',), ('driver',), ('gunner',), ('loader',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('france', 'f84somuasm'): (
        ('germany', 'e100'),
        'heavyTank',
        8,
        (('commander', 'loader'), ('driver',), ('gunner', 'loader'), ('radioman', 'loader')),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('france', 'f87batignolleschatillon12t'): (
        ('germany', 'pziij'),
        'lightTank',
        8,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('france', 'f88amx13105'): (
        ('france', 'amx1375'),
        'lightTank',
        10,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('france', 'f89canondassautde105'): (
        ('germany', 'jagdpziv'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('france', 'f97elceven90'): (
        ('ussr', 't46'),
        'lightTank',
        8,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('germany', 'g03pzvpanthertraining'): (
        ('germany', 'pzv'),
        'mediumTank',
        1,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g100gtraktorkrupp'): (
        ('uk', 'gb68matildablackprince'),
        'mediumTank',
        3,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('germany', 'g101stugiii'): (
        ('germany', 'stugiii'),
        'AT-SPG',
        4,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g102pziii'): (
        ('usa', 'm24chaffee'),
        'lightTank',
        3,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g102pziiibootcamp'): (
        ('usa', 'm24chaffee'),
        'lightTank',
        2,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g103ru251'): (
        ('ussr', 't502'),
        'lightTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g104stugiv'): (
        ('usa', 't28prototype'),
        'AT-SPG',
        5,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('germany', 'g105t55nvaddr'): (
        ('china', 'ch01type59'),
        'mediumTank',
        9,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g106pzkpfwpantherausff'): (
        ('germany', 'pantherm10'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g107pzkpfwiiiausfk'): (
        ('uk', 'gb21cromwell'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g108pzkpfwiiausfd'): (
        ('germany', 'pzii'),
        'lightTank',
        2,
        (('commander', 'gunner'), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('germany', 'g109steyrwt'): (
        ('ussr', 'su101'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g10pziiiausfjtraining'): (
        ('uk', 'gb21cromwell'),
        'mediumTank',
        1,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g110typ205'): (
        ('germany', 'maus'),
        'heavyTank',
        9,
        (('commander',), ('radioman',), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('germany', 'g112kanonenjagdpanzer'): (
        ('ussr', 'su100'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g112kanonenjagdpanzer105'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g113spic'): (
        ('germany', 'ltraktor'),
        'lightTank',
        7,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('germany', 'g114rheinmetallskorpian'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        8,
        (('commander', 'loader'), ('radioman',), ('driver',), ('gunner',)),
        ((0, 0), (3, 0), (2, 0), (1, 0)),
    ),
    ('germany', 'g114skorpian'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        8,
        (('commander', 'loader'), ('radioman',), ('driver',), ('gunner',)),
        ((0, 0), (3, 0), (2, 0), (1, 0)),
    ),
    ('germany', 'g115typ205b'): (
        ('uk', 'gb10blackprince'),
        'heavyTank',
        8,
        (('commander',), ('radioman',), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('germany', 'g115typ2054jun'): (
        ('uk', 'gb10blackprince'),
        'heavyTank',
        8,
        (('commander',), ('radioman',), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('germany', 'g116turaniiiprot'): (
        ('germany', 't25'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g117toldiiii'): (
        ('usa', 'm22locust'),
        'lightTank',
        3,
        (('commander', 'radioman'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('germany', 'g117toldiiiibootcamp'): (
        ('usa', 'm22locust'),
        'lightTank',
        2,
        (('commander', 'radioman'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('germany', 'g118vk4503'): (
        ('germany', 'pzvibtigerii'),
        'heavyTank',
        7,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g119panzer58'): (
        ('usa', 't69'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g119panzer58bf'): (
        ('usa', 't69'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g119pz58mutz'): (
        ('usa', 't69'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g120m4190'): (
        ('france', 'renaultft'),
        'lightTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (0, 1), (0, 2)),
    ),
    ('germany', 'g120m4190grandfinal'): (
        ('france', 'renaultft'),
        'lightTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (0, 1), (0, 2)),
    ),
    ('germany', 'g121grille15l63'): (
        ('france', 'renaultue57'),
        'AT-SPG',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('germany', 'g122vk6501h'): (
        ('uk', 'gb10blackprince'),
        'heavyTank',
        5,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (3, 0), (2, 0), (4, 0)),
    ),
    ('germany', 'g125spz57rh'): (
        ('ussr', 'btsv'),
        'lightTank',
        10,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g126hwk12'): (
        ('usa', 't1cunningham'),
        'lightTank',
        8,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (0, 1)),
    ),
    ('germany', 'g134pzkpfwvii'): (
        ('germany', 'vk4502p'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g136tiger131'): (
        ('usa', 't14'),
        'heavyTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g137pzvitiger217'): (
        ('germany', 'pzvibtigerii'),
        'heavyTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g138vk16802'): (
        ('ussr', 'object252'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('radioman',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (1, 0), (3, 1), (3, 2)),
    ),
    ('germany', 'g16pzvibtigeriitraining'): (
        ('germany', 'pzvibtigerii'),
        'heavyTank',
        1,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g39marderiii'): (
        ('usa', 't40'),
        'AT-SPG',
        4,
        (('commander', 'gunner'), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g40nashorn'): (
        ('ussr', 'gaz74b'),
        'AT-SPG',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('germany', 'g43stureremil'): (
        ('ussr', 'gaz74b'),
        'AT-SPG',
        7,
        (('commander',), ('radioman',), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (3, 1)),
    ),
    ('germany', 'g48e25'): (
        ('ussr', 'su100'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g48e25igr'): (
        ('ussr', 'su100'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g53pzi'): (
        ('germany', 'vk2801'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('germany', 'g58vk4502p7'): (
        ('germany', 'vk4502p'),
        'heavyTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g63pziausfc'): (
        ('usa', 'm2lt'),
        'lightTank',
        3,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('germany', 'g76pzsflivc'): (
        ('usa', 'm18hellcat'),
        'AT-SPG',
        5,
        (('commander', 'radioman'), ('gunner',), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (4, 0), (2, 0), (3, 0), (4, 1)),
    ),
    ('germany', 'g80pzivausfd'): (
        ('germany', 'e50'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g80pzivausfdbootcamp'): (
        ('germany', 'e50'),
        'mediumTank',
        2,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g81pzivausfh'): (
        ('germany', 'pziiiiv'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g82pziiausfg'): (
        ('usa', 'm2lt'),
        'lightTank',
        3,
        (('commander', 'gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g83pzivausfa'): (
        ('usa', 'shermanjumbo'),
        'mediumTank',
        3,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g85aufpanther'): (
        ('germany', 'vk1602'),
        'lightTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (3, 1)),
    ),
    ('germany', 'g85aufklarungspanzerv'): (
        ('germany', 'vk1602'),
        'lightTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (3, 1)),
    ),
    ('germany', 'g86vk2001db'): (
        ('usa', 'm4sherman'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g87vk3002dbv1'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g88indienpanzer'): (
        ('ussr', 't62a'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g89leopard1'): (
        ('usa', 't69'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g90dwii'): (
        ('uk', 'gb09churchillvii'),
        'heavyTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g91proaga'): (
        ('uk', 'gb07matilda'),
        'mediumTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('germany', 'g92vk7201'): (
        ('germany', 'vk4502p'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g93gwmkvie'): (
        ('ussr', 'object261'),
        'SPG',
        2,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('germany', 'g94gwtigerp'): (
        ('germany', 'ge'),
        'SPG',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('germany', 'g95pzsflivb'): (
        ('germany', 'hummel'),
        'SPG',
        4,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g96vk3002m'): (
        ('germany', 'pziiiiv'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('germany', 'g97waffentrageriv'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        9,
        (('commander',), ('radioman',), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (4, 0), (4, 1)),
    ),
    ('germany', 'g98waffentragere100'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('germany', 'g98waffentragere100p'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('germany', 'g99rhbwaffentrager'): (
        ('germany', 'dickermax'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('japan', 'j01nc27'): (
        ('france', 'renaultft'),
        'lightTank',
        1,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('japan', 'j01nc27bot'): (
        ('france', 'renaultft'),
        'lightTank',
        1,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('japan', 'j02teke'): (
        ('ussr', 'ms1'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('japan', 'j03hago'): (
        ('germany', 'pz35t'),
        'lightTank',
        2,
        (('commander', 'gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('japan', 'j04keni'): (
        ('germany', 'vk2801'),
        'lightTank',
        3,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('japan', 'j04kenibootcamp'): (
        ('germany', 'vk2801'),
        'lightTank',
        2,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('japan', 'j05kenib'): (
        ('germany', 'pziij'),
        'lightTank',
        3,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('japan', 'j06keho'): (
        ('usa', 'mtls1g14'),
        'lightTank',
        4,
        (('commander', 'loader'), ('gunner',), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j07chiha'): (
        ('germany', 'pziii'),
        'mediumTank',
        3,
        (('commander',), ('gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j08chinu'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j09chihe'): (
        ('usa', 'm4sherman'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j10chito'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j11chiri'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j11chiriigr'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j12chinukai'): (
        ('uk', 'gb21cromwell'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j13sta1'): (
        ('uk', 'gb07matilda'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j13sta1igr'): (
        ('uk', 'gb07matilda'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j14type61'): (
        ('uk', 'gb07matilda'),
        'mediumTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j15chini'): (
        ('ussr', 't62a'),
        'mediumTank',
        2,
        (('commander', 'gunner', 'loader'), ('driver',), ('radioman',)),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j16stb1'): (
        ('usa', 't54e1'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j16stb1igr'): (
        ('usa', 't54e1'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j18sta23'): (
        ('usa', 't69'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j19tigerijpn'): (
        ('germany', 'pzvibtigerii'),
        'heavyTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j20type2605'): (
        ('germany', 'e100'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('japan', 'j21type91'): (
        ('ussr', 'object252'),
        'heavyTank',
        3,
        (('commander', 'loader'), ('gunner',), ('driver',), ('radioman',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('japan', 'j22type95'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        4,
        (('commander', 'loader'), ('driver',), ('gunner',), ('radioman',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('japan', 'j22type95bootcamp'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        2,
        (('commander', 'loader'), ('driver',), ('gunner',), ('radioman',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
    ),
    ('japan', 'j23mito'): (
        ('germany', 'lowe'),
        'heavyTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('japan', 'j24mito130tons'): (
        ('germany', 'lowe'),
        'heavyTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('japan', 'j25type4'): (
        ('germany', 'e100'),
        'heavyTank',
        9,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('japan', 'j26type89'): (
        ('uk', 'gb06vickersmediummkiii'),
        'mediumTank',
        2,
        (('commander', 'loader'), ('gunner',), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('japan', 'j27oi120'): (
        ('germany', 'e100'),
        'heavyTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('japan', 'j28oi100'): (
        ('usa', 't14'),
        'heavyTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('japan', 'j29nameless'): (
        ('usa', 't14'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('japan', 'j30edelweiss'): (
        ('germany', 'pantherm10'),
        'mediumTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('poland', 'pl03pzvpoland'): (
        ('germany', 'pzv'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('sweden', 's01strv74a2'): (
        ('france', 'lorraine40t'),
        'mediumTank',
        6,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('sweden', 's02strvm42'): (
        ('uk', 'gb23centurion'),
        'mediumTank',
        5,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('sweden', 's03strvm38'): (
        ('ussr', 't26'),
        'lightTank',
        2,
        (('commander', 'radioman'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('sweden', 's04lagoi'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        4,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('sweden', 's05strvm2129'): (
        ('germany', 'ltraktor'),
        'lightTank',
        1,
        (('commander', 'gunner'), ('driver',), ('loader',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (2, 1)),
    ),
    ('sweden', 's06ikv90typbbofors'): (
        ('ussr', 'su100m1'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('sweden', 's07strv74'): (
        ('uk', 'gb23centurion'),
        'mediumTank',
        6,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('sweden', 's08ikv65alt2'): (
        ('germany', 'jagdpziv'),
        'AT-SPG',
        6,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('sweden', 's09l120td'): (
        ('germany', 'dickermax'),
        'AT-SPG',
        2,
        (('commander', 'radioman'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('sweden', 's10strv1030series'): (
        ('ussr', 'su100y'),
        'AT-SPG',
        9,
        (('commander', 'gunner'), ('driver', 'gunner'), ('radioman', 'loader')),
        ((0, 0), (3, 0), (4, 0)),
    ),
    ('sweden', 's11strv103b'): (
        ('ussr', 'su100y'),
        'AT-SPG',
        10,
        (('commander', 'gunner'), ('driver', 'gunner'), ('radioman', 'loader')),
        ((0, 0), (3, 0), (4, 0)),
    ),
    ('sweden', 's12strvm40'): (
        ('ussr', 't26'),
        'lightTank',
        3,
        (('commander', 'radioman'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('sweden', 's13leo'): (
        ('germany', 'vk3002db'),
        'mediumTank',
        7,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('sweden', 's14ikv103'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        5,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('sweden', 's15l60'): (
        ('ussr', 'bt2'),
        'lightTank',
        2,
        (('commander', 'radioman'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('sweden', 's16kranvagn'): (
        ('china', 'ch03wz111'),
        'heavyTank',
        10,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('sweden', 's17emil1952e2'): (
        ('china', 'ch03wz111'),
        'heavyTank',
        9,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('sweden', 's18emil1951e1'): (
        ('france', 'amx50120'),
        'heavyTank',
        8,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('sweden', 's19savm43'): (
        ('germany', 'hetzer'),
        'AT-SPG',
        4,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('sweden', 's20ikv72'): (
        ('france', 's35ca'),
        'AT-SPG',
        3,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('sweden', 's21udes03'): (
        ('france', 'renaultue57'),
        'AT-SPG',
        8,
        (('commander', 'gunner'), ('driver', 'gunner'), ('radioman', 'loader')),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('sweden', 's22strvs1'): (
        ('usa', 't110e4'),
        'AT-SPG',
        8,
        (('commander', 'gunner'), ('driver', 'gunner'), ('radioman', 'loader')),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('sweden', 's23strv81'): (
        ('uk', 'gb23centurion'),
        'mediumTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('sweden', 's23strv81sabaton'): (
        ('uk', 'gb23centurion'),
        'mediumTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('loader',), ('radioman',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1)),
    ),
    ('uk', 'gb14m2'): (
        ('usa', 'm3stuart'),
        'lightTank',
        2,
        (('commander', 'loader'), ('gunner',), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb15stuarti'): (
        ('usa', 'm3stuart'),
        'lightTank',
        3,
        (('commander', 'loader'), ('gunner',), ('driver',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb17granti'): (
        ('usa', 'm3grant'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('gunner',), ('driver',), ('loader', 'radioman'), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (5, 0), (4, 0)),
    ),
    ('uk', 'gb19shermanfirefly'): (
        ('ussr', 't54'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb25loydguncarriage'): (
        ('france', '105lefh18b2'),
        'SPG',
        2,
        (('commander', 'gunner', 'radioman'), ('loader',), ('driver',)),
        ((0, 0), (3, 0), (2, 0)),
    ),
    ('uk', 'gb26birchgun'): (
        ('france', 'batchatillon155'),
        'SPG',
        4,
        (('commander', 'radioman'), ('gunner',), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (3, 0), (2, 0), (4, 0), (3, 1)),
    ),
    ('uk', 'gb27sexton'): (
        ('usa', 't82'),
        'SPG',
        3,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('uk', 'gb28bishop'): (
        ('ussr', 'su18'),
        'SPG',
        5,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (1, 1), (0, 1)),
    ),
    ('uk', 'gb29crusader5inch'): (
        ('france', 'amx13f3am'),
        'SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb30fv3805'): (
        ('ussr', 'object212'),
        'SPG',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb31conquerorgun'): (
        ('ussr', 'su14'),
        'SPG',
        10,
        (('commander', 'radioman'), ('gunner',), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb32tortoise'): (
        ('germany', 'jagdpanther'),
        'AT-SPG',
        9,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (4, 0), (4, 1)),
    ),
    ('uk', 'gb33sentinelaci'): (
        ('usa', 'm4a2e4'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb35sentinelaciv'): (
        ('china', 'ch01type59'),
        'mediumTank',
        6,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1)),
    ),
    ('uk', 'gb39universalcarrierqf2'): (
        ('usa', 't28'),
        'AT-SPG',
        2,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb40guncarrierchurchill'): (
        ('usa', 't28'),
        'AT-SPG',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb41challenger'): (
        ('usa', 't30'),
        'AT-SPG',
        7,
        (('commander',), ('gunner',), ('driver',), ('loader',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb42valentineat'): (
        ('france', 'fcm36pak40'),
        'AT-SPG',
        3,
        (('commander', 'gunner', 'radioman'), ('driver',), ('loader',)),
        ((0, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb44archer'): (
        ('ussr', 'su101'),
        'AT-SPG',
        5,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('uk', 'gb45achillesiic'): (
        ('usa', 'm36slagger'),
        'AT-SPG',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb48fv215b183'): (
        ('ussr', 'object263'),
        'AT-SPG',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb50shermaniii'): (
        ('usa', 'shermanjumbo'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb51excelsior'): (
        ('usa', 'm6a2e1'),
        'heavyTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb52a45'): (
        ('ussr', 'churchillll'),
        'heavyTank',
        7,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb57alecto'): (
        ('germany', 'g20marderii'),
        'AT-SPG',
        4,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (2, 1)),
    ),
    ('uk', 'gb70nfv4202105'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb72at15'): (
        ('germany', 'jagdpziv'),
        'AT-SPG',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('uk', 'gb72at15igr'): (
        ('germany', 'jagdpziv'),
        'AT-SPG',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('uk', 'gb73at2'): (
        ('usa', 't18'),
        'AT-SPG',
        5,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('uk', 'gb74at8'): (
        ('france', 'amx50foch'),
        'AT-SPG',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2)),
    ),
    ('uk', 'gb75at7'): (
        ('uk', 'gb71at15a'),
        'AT-SPG',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb76mkvic'): (
        ('france', 'elcamx'),
        'lightTank',
        2,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (1, 0), (1, 1)),
    ),
    ('uk', 'gb77fv304'): (
        ('ussr', 'object212'),
        'SPG',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb77fv304igr'): (
        ('ussr', 'object212'),
        'SPG',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb78sextoni'): (
        ('usa', 'm37'),
        'SPG',
        3,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb79fv206'): (
        ('ussr', 'su14'),
        'SPG',
        8,
        (('commander', 'radioman'), ('gunner',), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('uk', 'gb80charioteer'): (
        ('usa', 't28prototype'),
        'AT-SPG',
        8,
        (('commander', 'gunner'), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('uk', 'gb81fv4004'): (
        ('usa', 't30'),
        'AT-SPG',
        9,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('uk', 'gb83fv4005'): (
        ('usa', 't110e4'),
        'AT-SPG',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb84chieftainmk6'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('uk', 'gb85cromwellberlin'): (
        ('uk', 'gb21cromwell'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('uk', 'gb86centurionactionx'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb87chieftaint95turret'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb88t95chieftainturret'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        10,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb91superconqueror'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        10,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('uk', 'gb92fv217'): (
        ('germany', 'jagdpanther'),
        'AT-SPG',
        10,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (1, 0), (4, 0), (4, 1)),
    ),
    ('uk', 'gb93caernarvonax'): (
        ('uk', 'gb11caernarvon'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a100t49'): (
        ('uk', 'gb60covenanter'),
        'lightTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a101m56'): (
        ('ussr', 'su100m1'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a102t28concept'): (
        ('usa', 't110e4'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a103t71e1'): (
        ('france', 'amx1390'),
        'lightTank',
        7,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('usa', 'a103t71e1igr'): (
        ('france', 'amx1390'),
        'lightTank',
        7,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('usa', 'a104m4a3e8a'): (
        ('usa', 'shermanjumbo'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a106m48a2120'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a107t1hmc'): (
        ('germany', 'bisoni'),
        'SPG',
        2,
        (('commander', 'gunner', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a108t18hmc'): (
        ('france', 'renaultbs'),
        'SPG',
        3,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (1, 0), (1, 1)),
    ),
    ('usa', 'a109t56gmc'): (
        ('ussr', 'object263'),
        'AT-SPG',
        3,
        (('commander', 'gunner'), ('gunner',), ('driver',), ('loader',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a111t25pilot'): (
        ('usa', 'pershing'),
        'mediumTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a112t71e2'): (
        ('ussr', 'ms1'),
        'lightTank',
        7,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (0, 1), (0, 2)),
    ),
    ('usa', 'a112t71e2r'): (
        ('ussr', 'ms1'),
        'lightTank',
        7,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (0, 1), (0, 2)),
    ),
    ('usa', 'a115chryslerk'): (
        ('germany', 'vk4502p'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('usa', 'a116xm551'): (
        ('france', 'hotchkissh35'),
        'lightTank',
        10,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (1, 0), (0, 1), (0, 2)),
    ),
    ('usa', 'a117t26e5'): (
        ('china', 'ch03wz111'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1)),
    ),
    ('usa', 'a117t26e5patriot'): (
        ('china', 'ch03wz111'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (3, 1)),
    ),
    ('usa', 'a118m4thunderbolt'): (
        ('usa', 'shermanjumbo'),
        'mediumTank',
        6,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a120m48a5'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a120m48a5igr'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a13t34hvybf'): (
        ('usa', 't34hvy'),
        'heavyTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('usa', 'a46t3'): (
        ('germany', 'stugiii'),
        'AT-SPG',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('usa', 'a63m46pattonkr'): (
        ('uk', 'gb21cromwell'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a78m4improved'): (
        ('usa', 'shermanjumbo'),
        'mediumTank',
        5,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a81t95e2'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a86t23e3'): (
        ('germany', 'pziv'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('usa', 'a87m44'): (
        ('germany', 'hummel'),
        'SPG',
        6,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('usa', 'a88m5355'): (
        ('ussr', 'object212'),
        'SPG',
        9,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0), (5, 0), (3, 0)),
    ),
    ('usa', 'a92m60'): (
        ('uk', 'gb70fv4202105'),
        'mediumTank',
        10,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a93t7combatcar'): (
        ('germany', 't15'),
        'lightTank',
        2,
        (('commander', 'gunner'), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a94t37'): (
        ('uk', 'gb60covenanter'),
        'lightTank',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a95t95e6'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a97m41bulldog'): (
        ('uk', 'gb60covenanter'),
        'lightTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('usa', 'a99t92lt'): (
        ('germany', 'vk1602'),
        'lightTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (1, 0)),
    ),
    ('ussr', 'r100su122a'): (
        ('usa', 't92'),
        'SPG',
        5,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('ussr', 'r101mt25'): (
        ('germany', 'pz38t'),
        'lightTank',
        6,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (3, 0), (2, 0), (1, 0), (3, 1)),
    ),
    ('ussr', 'r104object430ii'): (
        ('usa', 't2med'),
        'mediumTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (1, 1)),
    ),
    ('ussr', 'r105bt7a'): (
        ('ussr', 'bt2'),
        'lightTank',
        3,
        (('commander', 'radioman'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('ussr', 'r106kv85'): (
        ('ussr', 'is8'),
        'heavyTank',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r106kv85igr'): (
        ('ussr', 'is8'),
        'heavyTank',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r107ltb'): (
        ('usa', 't21'),
        'lightTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('ussr', 'r108t3485m'): (
        ('ussr', 't3485'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r109t54s'): (
        ('china', 'ch02type62'),
        'lightTank',
        9,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r110object260'): (
        ('usa', 't110'),
        'heavyTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r111isu130'): (
        ('ussr', 'su100'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r112t5445'): (
        ('ussr', 't62a'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r113object730'): (
        ('ussr', 'object252'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r114object244'): (
        ('usa', 't5758'),
        'heavyTank',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r115is3auto'): (
        ('usa', 'm6a2e1'),
        'heavyTank',
        8,
        (('commander', 'radioman', 'loader'), ('gunner', 'loader'), ('driver',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('ussr', 'r116isu122cberlin'): (
        ('ussr', 'su152'),
        'AT-SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r117t3485rudy'): (
        ('ussr', 'matildaiill'),
        'mediumTank',
        6,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r118t28f30'): (
        ('ussr', 't28'),
        'mediumTank',
        4,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',), ('radioman',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('ussr', 'r119object777'): (
        ('usa', 't110'),
        'heavyTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r120t22sra22'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r121kv4ktt'): (
        ('germany', 'jagdpze100'),
        'AT-SPG',
        8,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0)),
    ),
    ('ussr', 'r122t44100'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r122t44100b'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r123kirovets1'): (
        ('france', 'fcm50t'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('ussr', 'r125t45'): (
        ('france', 'elcamx'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (1, 0)),
    ),
    ('ussr', 'r126object7305'): (
        ('usa', 't28prototype'),
        'AT-SPG',
        10,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0), (3, 0)),
    ),
    ('ussr', 'r127t44100p'): (
        ('china', 'ch01type59'),
        'mediumTank',
        8,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r128kv4kreslavskiy'): (
        ('usa', 't14'),
        'heavyTank',
        8,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0), (4, 1)),
    ),
    ('ussr', 'r129object257'): (
        ('france', 'amx50120'),
        'heavyTank',
        10,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('ussr', 'r131tankgavalov'): (
        ('germany', 'pz38t'),
        'lightTank',
        7,
        (('commander',), ('driver',), ('gunner',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (3, 0), (2, 0)),
    ),
    ('ussr', 'r132vnii100lt'): (
        ('ussr', 't46'),
        'lightTank',
        10,
        (('commander', 'radioman', 'loader'), ('driver',), ('gunner', 'loader')),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('ussr', 'r133kv122'): (
        ('usa', 't110'),
        'heavyTank',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r134object252k'): (
        ('ussr', 'is3'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('ussr', 'r134object252u'): (
        ('ussr', 'is3'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('ussr', 'r135t103'): (
        ('usa', 't30'),
        'AT-SPG',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0), (5, 0)),
    ),
    ('ussr', 'r139is2sh'): (
        ('uk', 'gb13fv215b'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0)),
    ),
    ('ussr', 'r140m4loza'): (
        ('usa', 'm4a3e8sherman'),
        'mediumTank',
        6,
        (('commander',), ('driver',), ('gunner',), ('radioman',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r143t29'): (
        ('ussr', 't3485'),
        'mediumTank',
        3,
        (('commander',), ('driver',), ('gunner', 'loader'), ('radioman',), ('radioman',)),
        ((0, 0), (3, 0), (1, 0), (2, 0), (4, 0)),
    ),
    ('ussr', 'r145object705a'): (
        ('germany', 'maus'),
        'heavyTank',
        10,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r146stg'): (
        ('france', 'batchatillon25t'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (1, 1)),
    ),
    ('ussr', 'r146stgtday'): (
        ('france', 'batchatillon25t'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (1, 1)),
    ),
    ('ussr', 'r148object430u'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r149object2684'): (
        ('usa', 't110e4'),
        'AT-SPG',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r151object2572'): (
        ('france', 'bdrg1b'),
        'heavyTank',
        9,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('ussr', 'r153object705'): (
        ('germany', 'pzvi'),
        'heavyTank',
        9,
        (('commander', 'radioman'), ('driver',), ('gunner',), ('loader',)),
        ((0, 0), (2, 0), (1, 0), (4, 0)),
    ),
    ('ussr', 'r42t60'): (
        ('usa', 'm2lt'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('ussr', 'r43t70'): (
        ('usa', 'm2lt'),
        'lightTank',
        3,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('ussr', 'r43t70bootcamp'): (
        ('usa', 'm2lt'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman', 'loader'), ('driver',)),
        ((0, 0), (2, 0)),
    ),
    ('ussr', 'r44t80'): (
        ('usa', 't2lt'),
        'lightTank',
        4,
        (('commander', 'radioman', 'loader'), ('gunner',), ('driver',)),
        ((0, 0), (2, 0), (1, 0)),
    ),
    ('ussr', 'r50su76i'): (
        ('ussr', 'su85i'),
        'AT-SPG',
        3,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r50su76ibootcamp'): (
        ('ussr', 'su85i'),
        'AT-SPG',
        2,
        (('commander',), ('gunner',), ('driver',), ('loader', 'radioman')),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r57a43'): (
        ('ussr', 't3485'),
        'mediumTank',
        6,
        (('commander',), ('gunner',), ('radioman',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0)),
    ),
    ('ussr', 'r59a44'): (
        ('usa', 't2med'),
        'mediumTank',
        7,
        (('commander',), ('gunner',), ('driver',), ('radioman',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (1, 1), (1, 2)),
    ),
    ('ussr', 'r60object416'): (
        ('usa', 't2med'),
        'mediumTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (1, 1)),
    ),
    ('ussr', 'r61object252bf'): (
        ('ussr', 'object252'),
        'heavyTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r71is2b'): (
        ('usa', 't5758'),
        'heavyTank',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r86ltp'): (
        ('ussr', 'valentinell'),
        'lightTank',
        3,
        (('commander', 'gunner', 'radioman'), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('ussr', 'r86ltpbootcamp'): (
        ('ussr', 'valentinell'),
        'lightTank',
        2,
        (('commander', 'gunner', 'radioman'), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0)),
    ),
    ('ussr', 'r91su141'): (
        ('france', 'amx105am'),
        'SPG',
        7,
        (('commander', 'radioman'), ('gunner',), ('gunner',), ('driver',), ('loader',), ('loader',)),
        ((0, 0), (1, 0), (3, 0), (2, 0), (3, 1), (3, 2)),
    ),
    ('ussr', 'r95object907'): (
        ('usa', 't69'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r95object907a'): (
        ('usa', 't69'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r96object430'): (
        ('ussr', 't62a'),
        'mediumTank',
        9,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r96object430b'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r97object140'): (
        ('ussr', 't62a'),
        'mediumTank',
        10,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r98t4485'): (
        ('ussr', 't62a'),
        'mediumTank',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r98t4485m'): (
        ('ussr', 't62a'),
        'lightTank',
        8,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
    ('ussr', 'r99t44122'): (
        ('ussr', 't62a'),
        'mediumTank',
        7,
        (('commander', 'radioman'), ('gunner',), ('driver',), ('loader',)),
        ((0, 0), (1, 0), (2, 0), (3, 0)),
    ),
}
