"""Regenerate pure #1513 editor bounds/bases/fingerprints; no client artwork."""
from pathlib import Path
import hashlib
import json
import pprint
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src/res/scripts/client'))
from gui.mods.offline_lan_0922.ai.maps import TACTICAL_MAPS


def build():
    entries = {}
    for path in sorted((ROOT / 'navgraphs').glob('*.json')):
        if path.name == 'manifest.json':
            continue
        raw = path.read_bytes()
        graph = json.loads(raw)
        if 'map' not in graph:
            continue
        name = graph['map']
        entries[name] = dict(bounds=list(TACTICAL_MAPS[name]['bounds']),
                             bases=graph['bases'],
                             resource_sha256=hashlib.sha256(raw).hexdigest())
    if len(entries) != 41:
        raise RuntimeError('Expected the pinned 41-map registry')
    return entries


if __name__ == '__main__':
    path = ROOT / 'src/res/scripts/client/gui/mods/offline_lan_0922/bot_editor_maps.py'
    header = ('# -*- coding: utf-8 -*-\n'
              '"""Exact #1513 authoring bounds, bases and baked resource identity.\n'
              'Generated by tools/build_bot_editor_maps.py; no client artwork.\n"""\n')
    path.write_text(header + 'MAPS = ' + pprint.pformat(build(), sort_dicts=True) + '\n', encoding='utf8')
